language: node_js

node_js:
- 6.1.0

dist: trusty

sudo: required

services:
- postgresql

before_script:
- psql -c 'drop database if exists apatite;' -U postgres
- psql -c 'create database apatite;' -U postgres
- npm install pg@6.0.0
- mysql -e "drop database if exists apatite;" -uroot
- mysql -e "create database IF NOT EXISTS apatite;" -uroot
- mysql -e "CREATE USER 'apatite'@'localhost' IDENTIFIED BY 'apatite';" -uroot
- mysql -e "GRANT ALL PRIVILEGES ON apatite.* TO 'apatite'@'localhost' WITH GRANT OPTION;" -uroot
- mysql -e "SET GLOBAL sql_mode = 'STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';"
  -uroot
- npm install mysql@2.11.1

addons:
  postgresql: '9.4'
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

after_success:
- npm install istanbul@0.4.4
- npm install coveralls@2.11.9
- npm install mocha-lcov-reporter@1.2.0
- ./node_modules/.bin/istanbul cover ./node_modules/.bin/_mocha --report lcovonly
  -- -R spec --recursive && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  && rm -rf ./coverage