language: node_js

node_js:
- 6.1.0
- 6.3.1
- 6.9.1

dist: trusty

sudo: required

services:
- postgresql

before_script:
- psql -c "DROP DATABASE IF EXISTS apatite;" -U postgres
- psql -c "CREATE DATABASE apatite;" -U postgres
- psql -c "CREATE USER apatite WITH PASSWORD 'Nodejs20090527!' SUPERUSER INHERIT CREATEDB CREATEROLE NOREPLICATION;" -U postgres
- npm install pg@6.0.0
- mysql -e "drop database if exists apatite;" -uroot
- mysql -e "create database IF NOT EXISTS apatite;" -uroot
- mysql -e "CREATE USER 'apatite'@'localhost' IDENTIFIED BY 'Nodejs20090527!';" -uroot
- mysql -e "GRANT ALL PRIVILEGES ON apatite.* TO 'apatite'@'localhost' WITH GRANT OPTION;" -uroot
- mysql -e "SET GLOBAL sql_mode = 'STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';" -uroot
- npm install mysql@2.11.1

addons:
  postgresql: '9.4'
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6