language: node_js
node_js:
 - "6.1.0"

after_success:
- npm install istanbul@0.4.4
- npm install coveralls@2.11.9
- npm install mocha-lcov-reporter@1.2.0
- ./node_modules/.bin/istanbul cover ./node_modules/.bin/_mocha --recursive --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage