language: node_js
node_js:
 - "6.1.0"

services:
 - postgresql

before_script:
 - psql -c 'drop database if exists apatite;' -U postgres
 - psql -c 'create database apatite;' -U postgres
 - npm install pg@5.1.0
 - npm install pg-pool@1.1.0

addons:
 postgresql: "9.4"

after_success:
- npm install istanbul@0.4.4
- npm install coveralls@2.11.9
- npm install mocha-lcov-reporter@1.2.0
- ./node_modules/.bin/istanbul cover ./node_modules/.bin/_mocha --report lcovonly -- -R spec --recursive && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage